### ISSUE TITLE
noted about installation

### ISSUE THREAD

**Issue by powerspowers** [mdanics/fluttergram#28]
Hi - in your setup instructions it should be pointed out that you have to change the Bundle ID in XCode to match the one you create in Firebase that is in the GoogleService-Info.plist file. Also, the index for the insta_posts has to be created in Firebase. Still building the project, thanks for creating it!

**Comment by GustavoContreiras** [comment]
I founded the url link to create the index inspecting the debug console. Not everybody will see that.

`W/Firestore( 7503): (0.6.6-dev) [Firestore]: Listen for Query(insta_posts where ownerId == 117644910200781115007 order by timestamp) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: https://console.firebase.google.com/project/<YourProject>/database/firestore/indexes?create_index=EgtpbnN0YV9wb3N0cxoLCgdvd25lcklkEAIaDQoJdGltZXN0YW1wEAIaDAoIX19uYW1lX18QAg, cause=null}`

Happens when you click on your profile page on bottom navigation.
