### ISSUE TITLE
image take too long to upload and render on feed.

### ISSUE THREAD

**Issue by iammuhdimran** [mdanics/fluttergram#34]
Hello there, your Fluttergram code are incredible but i have slight problem with it.
The image that i uploaded is taking too long to upload.
Furthermore, it seem that the image of another person i follow is taking too long to appear on feed.
Do you know if there is any solution for me to make it faster?
Thank you.

**Comment by mdanics** [comment]
You could increase the compression in the uploader page

**Comment by amizanali** [comment]
how about the images that is taking longer to load, especially on the home feed and my profile feed? is there any way to make it load faster?

**Comment by amizanali** [comment]
> You could increase the compression in the uploader page

how about the images that is taking longer to load/render, especially on the home feed and my profile feed? is there any way to make it load/render faster?

**Comment by harshapulikollu** [comment]
Images take longer period time of time to load for 2 reasons 
1. If internet speed is slow.
2. Image size(resolution) is high(very big).
You can't do with anything for first reason.
For the second what you can do is increased the compression rate while uploading the pic to server (which will increase uploading time in less spec devices as compression might take a while) such that images will retrieve quickly as the image would be less in size.
Or the best way is -> use cloud functions [https://github.com/firebase/functions-samples/tree/Node-8/generate-thumbnail](checkout this official example) such that on every new upload into storage it will trigger and generate a thumbnail of that original image. This will give you the original image user uploaded and thumbnail of 100x100 (size of 1-3Kb) created by the cloud functions.
Then in your home page/feed first call the thumbnail image (starts with prefix _thumb) till original image loads. Once original loads swap thumbnail with original resolution image. (This is what Instagram do for faster loading that's why you see blur images first then original after it loads)

**Comment by randaalfakih** [comment]
Does anyone have an idea how I could navigate through a single bottom
navigation bar item with staying on the same tab without it dissapearing?

**Comment by mdanics** [comment]
@harshapulikollu explained it perfectly. Thank you.

**Comment by kamami** [comment]
@harshapulikollu any chance that you show how this is done? Sounds really nice and helpful!
