### ISSUE TITLE
Comments not visible

### ISSUE THREAD

**Issue by SpadeStudios** [mdanics/fluttergram#97]
@mdanics Comments page stuck at circular progress widget. Couldn't able to see comments. But its showing commented on logs. 
![comments](https://user-images.githubusercontent.com/67581536/86404163-c3a5e180-bccc-11ea-9f2a-2c4135f4677b.PNG)
Please help

**Comment by mdanics** [comment]
Any error logs?

**Comment by SpadeStudios** [comment]
@mdanics No error in logs.. In logs its showing commented and firestore db comments is storing successfully. But its not visible in comments screen. Tried your apk file as same issue occurring.

**Comment by mdanics** [comment]
The issue is that previously timestamps were stored as a String as they used to not be supported in the Firestore plugin. The fix is by changing the variable type for timestamp to `Timestamp` instead of `String`. 

It is fixed here: https://github.com/mdanics/fluttergram/pull/99

Note - the APK is not updated yet

**Comment by pinkasey** [comment]
Just dropping by to mention that I downloaded the demo apk, and saw this issue too.
Maybe worthwhile to update the apk.
